/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef defines_CONSTANTS_H
#define defines_CONSTANTS_H

#include "defines_types.h"

namespace scatsService {

class definesConstants {
 public:
  definesConstants();

};

extern const definesConstants g_defines_constants;

} // namespace

#endif
