/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "defines_constants.h"

namespace scatsService {

const definesConstants g_defines_constants;

definesConstants::definesConstants() {
}

} // namespace

