/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef scats_CONSTANTS_H
#define scats_CONSTANTS_H

#include "scats_types.h"

namespace scatsService {

class scatsConstants {
 public:
  scatsConstants();

};

extern const scatsConstants g_scats_constants;

} // namespace

#endif
